### PR TITLE
Minor cleanup, remove static process classes.

### PR DESCRIPTION
**Pull request by IanCa**

### CODE REVIEW

**Review by VisLab — COMMENTED** [review]
It seems like process_form and process_services should both either be classes or not?

**Comment by IanCa** [comment]
Yeah, I changed them both

**Comment by VisLab** [comment]
In thinking about this --- I am thinking that they should remain as classes.  The reason is that then we only have to import the class and can use the classname.x to access the various methods.  This is convenient for using it in MATLAB since we only need to import the class.

**Comment by IanCa** [comment]
Does matlab not support the module import?

In python it's exactly the same either way, this just makes the code
cleaner and the import simpler.

**Pull request closed without merging**
